# Generated by Django 5.0.2 on 2024-04-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_Id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Id', models.IntegerField(unique=True)),
            ],
        ),
    ]
