# Generated by Django 5.0.2 on 2024-04-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_blog_image_alter_blog_id_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='Pictures/%Y/%m/%d'),
        ),
    ]
