# Generated by Django 5.0.2 on 2024-04-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=128, unique=True)),
                ('Author_Id', models.IntegerField(unique=True)),
                ('Title', models.CharField(max_length=128)),
                ('Date', models.DateTimeField(auto_now=True)),
                ('Content', models.TextField()),
            ],
        ),
    ]
