# Generated by Django 5.0.2 on 2024-04-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Date',
        ),
    ]
