# Generated by Django 5.0.2 on 2024-04-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Author',
            field=models.CharField(max_length=128),
        ),
    ]
