# Generated by Django 5.0.2 on 2024-04-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_id_blog_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog_Id',
        ),
    ]
