# Generated by Django 5.0.2 on 2024-04-13 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_blog_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_id',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Blog_Id', models.IntegerField()),
            ],
        ),
    ]
