# Generated by Django 5.0.2 on 2024-04-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blog_id_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_Id',
            field=models.IntegerField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blog_id',
            name='Blog_Id',
            field=models.IntegerField(blank=True),
        ),
    ]
