# Generated by Django 5.0.2 on 2024-04-14 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blog_blog_id_alter_blog_id_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Blog_Id',
            field=models.IntegerField(unique=True),
        ),
    ]
