# Generated by Django 5.0.2 on 2024-04-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_blog_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Image',
            field=models.ImageField(blank=True, height_field='300px', null=True, upload_to='', width_field='300px'),
        ),
        migrations.AlterField(
            model_name='blog_id',
            name='Blog_Id',
            field=models.IntegerField(),
        ),
    ]
